import assert from 'node:assert/strict';
import test from 'node:test';
import {
  isSubmittedPromptRecord,
  userPromptRecordText,
} from '../src/claude-transcript-tail.mjs';

// Real records captured on 2026-08-03 from task 91 attempt 3, session a0c55566 in the Agreau
// project (Claude Code 2.1.220). CC Relay pasted at 14:26:00.620, right as a compaction of a 3MB
// conversation started, and Claude appended these AFTER the paste offset when /compact finished.
const COMMAND_NAME_TEXT = [
  '<command-name>/compact</command-name>',
  '<command-message>compact</command-message>',
  '<command-args></command-args>',
].join('\n');
const LOCAL_COMMAND_STDOUT_TEXT = '<local-command-stdout>Compacted. ctrl+o for history</local-command-stdout>';
const LOCAL_COMMAND_CAVEAT_TEXT = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>';
// NOT from the task 91 capture, whose compaction succeeded. This is the failure-path sibling of
// the stdout block, kept in the same class so a FAILING slash command cannot rebuild the freeze.
const LOCAL_COMMAND_STDERR_TEXT = '<local-command-stderr>Error: compaction failed</local-command-stderr>';

const userRecord = (content, extra = {}) => ({ type: 'user', message: { content }, ...extra });

test('slash-command bookkeeping records are not prompt-delivery evidence (task 91, 2026-08-03)', () => {
  // Index 203 in the capture. isMeta is ABSENT, so the executor's `isMeta !== true` guard cannot
  // drop it and the unmatched-submission latch fired on it, freezing paste and submit recovery.
  assert.equal(userPromptRecordText(userRecord(COMMAND_NAME_TEXT)), '');
  // Index 204. Also written with no isMeta flag.
  assert.equal(userPromptRecordText(userRecord(LOCAL_COMMAND_STDOUT_TEXT)), '');
  // Index 202. Captured with isMeta true, but the helper must drop it on its own so the caller's
  // isMeta guard is defence in depth rather than the only line of defence.
  assert.equal(userPromptRecordText(userRecord(LOCAL_COMMAND_CAVEAT_TEXT, { isMeta: true })), '');
  assert.equal(userPromptRecordText(userRecord(LOCAL_COMMAND_CAVEAT_TEXT)), '');
});

test('a FAILING slash command cannot rebuild the freeze: stderr is bookkeeping too', () => {
  // Hardening, not capture. Task 91's compaction succeeded, so only the stdout block was recorded.
  // A slash command that FAILS writes its diagnostics into the same wrapper with no isMeta flag,
  // which would recreate the task 91 latch freeze byte for byte. Same class, same treatment.
  assert.equal(userPromptRecordText(userRecord(LOCAL_COMMAND_STDERR_TEXT)), '');
  assert.equal(userPromptRecordText(userRecord(`\n  ${LOCAL_COMMAND_STDERR_TEXT}`)), '');
  assert.equal(
    userPromptRecordText(userRecord([{ type: 'text', text: LOCAL_COMMAND_STDERR_TEXT }])),
    '',
  );
  // Still only a leading marker. A prompt that talks about the block is a real prompt.
  const prompt = 'Explain why <local-command-stderr> shows up after a failed compaction.';
  assert.equal(userPromptRecordText(userRecord(prompt)), prompt);
});

test('leading whitespace before a bookkeeping marker does not smuggle the record through', () => {
  assert.equal(userPromptRecordText(userRecord(`\n  ${COMMAND_NAME_TEXT}`)), '');
  assert.equal(userPromptRecordText(userRecord(`  ${LOCAL_COMMAND_STDOUT_TEXT}\n`)), '');
});

test('a bare /compact user record still returns its text', () => {
  // Index 193 in the capture: the RAW slash-command record Claude writes when the human submits
  // the command, before the bookkeeping block. It is the record a slash-command prompt correlates
  // on, so dropping it would lose delivery evidence. The executor excludes it separately.
  assert.equal(userPromptRecordText(userRecord('/compact')), '/compact');
});

test('existing exclusions are unchanged', () => {
  const summary = 'This session is being continued from a previous conversation that ran out of context.';
  // Index 201: isCompactSummary true, isMeta ABSENT.
  assert.equal(userPromptRecordText(userRecord(summary, { isCompactSummary: true })), '');
  assert.equal(
    userPromptRecordText(userRecord([{ type: 'tool_result', tool_use_id: 't1', content: 'Ship it.' }])),
    '',
  );
  assert.equal(userPromptRecordText({ type: 'assistant', message: { content: 'Ship it.' } }), '');
});

test('a genuine submitted prompt still returns its text verbatim', () => {
  const prompt = 'Continue the Agreau valuation refactor and rerun the suite.';
  assert.equal(userPromptRecordText(userRecord(prompt)), prompt);
  // Returned byte for byte. normalizedPromptText only trimEnds, so leading whitespace is
  // load-bearing for the exact-equality path in submittedPromptMatches.
  assert.equal(userPromptRecordText(userRecord(`  ${prompt}\n\n`)), `  ${prompt}\n\n`);
});

test('the guard matches a leading marker, never a mention inside a real prompt', () => {
  const prompt = 'Fix the guard so <command-name> and <local-command-stdout> records are dropped.';
  assert.equal(userPromptRecordText(userRecord(prompt)), prompt);
  assert.equal(
    userPromptRecordText(userRecord([{ type: 'text', text: prompt }])),
    prompt,
  );
});

test('array content is judged on the joined text', () => {
  assert.equal(
    userPromptRecordText(userRecord([
      { type: 'text', text: '<command-name>/compact</command-name>' },
      { type: 'text', text: '<command-args></command-args>' },
    ])),
    '',
  );
  const blocks = [{ type: 'text', text: 'Ship the release' }, { type: 'text', text: 'and report back.' }];
  assert.equal(userPromptRecordText(userRecord(blocks)), 'Ship the release\nand report back.');
});

test('the task 91 compaction tail carries no prompt text out of its four compaction records', () => {
  // Indices 193 and 201 through 204 are the real capture. The executor reads from this turn's
  // injection offset, so all of them arrived after CC Relay pasted. The four compaction records
  // must read as empty, or the caller sees a submitted prompt it cannot match to any task and
  // stops paste and submit recovery for good. CC Relay's own pasted prompt never reached the
  // transcript in the incident, so the last row is a SYNTHETIC positive control proving the guard
  // still lets a genuine submission through.
  const prompt = 'Continue the Agreau valuation refactor.';
  const tail = [
    userRecord('/compact'), // index 193, the raw slash-command submission
    userRecord('This session is being continued from a previous conversation...', {
      isCompactSummary: true,
      isVisibleInTranscriptOnly: true,
    }), // index 201
    userRecord(LOCAL_COMMAND_CAVEAT_TEXT, { isMeta: true }), // index 202
    userRecord(COMMAND_NAME_TEXT), // index 203
    userRecord(LOCAL_COMMAND_STDOUT_TEXT), // index 204
    userRecord(prompt), // synthetic, not from the capture
  ];
  assert.deepEqual(tail.map(userPromptRecordText), ['/compact', '', '', '', '', prompt]);
  assert.deepEqual(
    tail.map((record) => isSubmittedPromptRecord(record, prompt)),
    [false, false, false, false, false, true],
  );
});
