import { execFile, spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { homedir as osHomedir } from 'node:os';
import { join } from 'node:path';

const DEFAULT_PROBE_TIMEOUT_MS = 3_000;
const FALLBACK_COMMAND = 'claude';

// Claude CLI 2.1.218 supports `agents --json`; 2.1.84 does not. Discovery and
// execution must therefore pin the newest binary instead of trusting whatever
// bare `claude` PATH resolution returns, which varies with how CC Relay was
// launched (Finder or dock versus a terminal).
const KNOWN_GOOD_VERSION = [2, 1, 218];

// Absolute locations that commonly hold a claude binary on macOS and Linux even
// when they are absent from the launching process PATH.
const WELL_KNOWN_POSIX = [
  '~/.local/bin/claude',
  '/opt/homebrew/bin/claude',
  '/usr/local/bin/claude',
  '/usr/bin/claude',
];

// Windows cannot run a provider CLI the way POSIX does. `claude` and `codex` install as npm
// shims named `claude.cmd` and `codex.cmd`, libuv only appends `.com` and `.exe` when it
// searches PATH, and Node refuses to spawn a `.cmd` or `.bat` file directly since the
// CVE-2024-27980 hardening. A shim therefore has to run through cmd.exe, and the whole command
// line has to be escaped by hand because cmd.exe is handed verbatim arguments.
const CMD_SHIM_PATTERN = /\.(?:cmd|bat)$/i;
// Every character cmd.exe treats specially. The space is deliberate: caret-escaping it is what
// keeps `C:\Program Files\nodejs\claude.cmd` a single token.
const CMD_META_CHARS = /([()\][%!^"`<>&|;, *?])/g;

function escapeCmdCommand(command) {
  return command.replace(CMD_META_CHARS, '^$1');
}

// Produces one argument that survives cmd.exe and arrives at the child intact. Every quote is
// caret-escaped, so cmd.exe never enters quoted state and strips exactly one caret layer,
// leaving standard C runtime quoting for the child's own parser. Shims generated by npm end in
// `%*`, which makes cmd.exe parse the tail a second time, so those need a second caret layer.
function escapeCmdArgument(value, doubleEscape) {
  let escaped = String(value);
  // Double the backslashes that precede a quote, then escape the quote itself.
  escaped = escaped.replace(/(\\*)"/g, '$1$1\\"');
  // Double the trailing backslashes so the closing quote stays a delimiter instead of literal.
  escaped = escaped.replace(/(\\*)$/, '$1$1');
  escaped = `"${escaped}"`;
  escaped = escaped.replace(CMD_META_CHARS, '^$1');
  if (doubleEscape) {
    escaped = escaped.replace(CMD_META_CHARS, '^$1');
  }
  return escaped;
}

// Shapes exactly one provider CLI invocation for the current platform. Returns the command,
// arguments, and the spawn options the caller must merge in. On POSIX this is an identity
// function, so macOS behaviour is byte-identical. On Windows it hides the console window a GUI
// parent would otherwise flash for every probe, and routes `.cmd` or `.bat` shims through
// cmd.exe with a fully escaped command line.
//
// Known residual limit: `%NAME%` inside an argument is still expanded by cmd.exe, because a
// caret cannot escape a percent sign on the command line. Only directory paths reach argv here.
export function providerCommandInvocation(command, args = [], { platform = process.platform, env = process.env } = {}) {
  const list = [...args].map((value) => String(value));
  if (platform !== 'win32') {
    return { command, args: list, options: {} };
  }
  const windowsOptions = { windowsHide: true };
  if (!CMD_SHIM_PATTERN.test(String(command))) {
    return { command, args: list, options: windowsOptions };
  }
  const commandLine = [
    escapeCmdCommand(String(command)),
    ...list.map((value) => escapeCmdArgument(value, true)),
  ].join(' ');
  return {
    command: env?.comspec || env?.ComSpec || env?.COMSPEC || 'cmd.exe',
    args: ['/d', '/s', '/c', `"${commandLine}"`],
    options: { ...windowsOptions, windowsVerbatimArguments: true },
  };
}

// Locates a bare command name the way Windows actually resolves one: every PATH entry crossed
// with the executable extensions, preferring a real `.exe` over a `.cmd` shim so the direct
// spawn path is used whenever it exists. Returns the name unchanged on POSIX, when the caller
// already holds a path, and when nothing matches, so no existing behaviour changes.
export function resolveExecutableOnPath(name, {
  env = process.env,
  platform = process.platform,
  fileExists = existsSync,
} = {}) {
  if (platform !== 'win32' || !name || /[\\/]/.test(name)) {
    return name;
  }
  const pathValue = env?.PATH || env?.Path || env?.path || '';
  for (const entry of pathValue.split(';')) {
    if (!entry) continue;
    for (const extension of ['.exe', '.com', '.cmd', '.bat']) {
      const candidate = join(entry, `${name}${extension}`);
      if (fileExists(candidate)) return candidate;
    }
  }
  return name;
}

// Windows has no process groups and no real signals, so `child.kill()` terminates only the
// direct child. When that child is cmd.exe wrapping a provider shim, the provider itself keeps
// running: a cancelled task would go on editing the workspace, and an orphaned Codex app-server
// would keep the shared port bound so the next start cannot bind it. `taskkill /T /F` is the
// Windows equivalent of a process-group kill. The direct kill stays as the fallback for when
// taskkill cannot be started at all.
export function terminateChildProcess(child, {
  signal = 'SIGTERM',
  platform = process.platform,
  spawnProcess = spawn,
} = {}) {
  if (!child) {
    return false;
  }
  if (platform === 'win32' && Number.isInteger(child.pid) && child.pid > 0) {
    try {
      const killer = spawnProcess('taskkill', ['/PID', String(child.pid), '/T', '/F'], {
        stdio: 'ignore',
        windowsHide: true,
      });
      killer?.on?.('error', () => {
        try {
          child.kill(signal);
        } catch {}
      });
      killer?.unref?.();
      return true;
    } catch {
      // taskkill could not be started, so fall through to the direct kill below
    }
  }
  return child.kill(signal);
}

function defaultExec(command, args, options) {
  return new Promise((resolve, reject) => {
    execFile(command, args, options, (error, stdout, stderr) => {
      if (error) {
        error.stderr = stderr;
        reject(error);
        return;
      }
      resolve(stdout);
    });
  });
}

function binaryNames(platform) {
  // On Windows the launcher is typically a shim (`claude.cmd`) or an executable,
  // so probe the common variants. POSIX installs use the bare name.
  return platform === 'win32' ? ['claude.cmd', 'claude.exe', 'claude'] : ['claude'];
}

function expandHome(path, homedir) {
  if (path === '~') return homedir;
  if (path.startsWith('~/')) return join(homedir, path.slice(2));
  return path;
}

// Enumerate every candidate path worth probing, in priority order: each PATH
// entry (in PATH order) followed by the well-known absolute locations. Paths are
// deduplicated so a location that appears in both is probed once, keeping the
// earliest position. Exported for direct unit testing of enumeration order.
export function enumerateCandidates({ env = process.env, platform = process.platform, homedir = osHomedir() } = {}) {
  const names = binaryNames(platform);
  const seen = new Set();
  const candidates = [];
  const add = (path) => {
    if (!path || seen.has(path)) return;
    seen.add(path);
    candidates.push(path);
  };
  const pathValue = env?.PATH || env?.Path || '';
  const delimiter = platform === 'win32' ? ';' : ':';
  for (const entry of pathValue.split(delimiter)) {
    if (!entry) continue;
    for (const name of names) {
      add(join(entry, name));
    }
  }
  if (platform === 'win32') {
    // The same reason the POSIX list exists applies here: a desktop launch inherits the
    // registry PATH, which lags behind an installer that just extended it, so the two standard
    // install destinations are probed directly. The native installer writes
    // %USERPROFILE%\.local\bin and a global npm install writes %APPDATA%\npm.
    for (const name of names) {
      add(join(homedir, '.local', 'bin', name));
    }
    const appData = env?.APPDATA || env?.AppData || '';
    if (appData) {
      for (const name of names) {
        add(join(appData, 'npm', name));
      }
    }
  } else {
    for (const location of WELL_KNOWN_POSIX) {
      add(expandHome(location, homedir));
    }
  }
  return candidates;
}

// Parse the leading semantic version from `claude --version` output such as
// "2.1.218 (Claude Code)". Returns null when no version is present.
export function parseClaudeVersion(output) {
  const match = /(\d+)\.(\d+)\.(\d+)/.exec(String(output || ''));
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

// Numeric component comparison. Lexical comparison is wrong here because
// "2.1.84" sorts above "2.1.218" as text while 218 is the newer patch.
export function compareVersions(left, right) {
  const a = left || [0, 0, 0];
  const b = right || [0, 0, 0];
  for (let index = 0; index < 3; index += 1) {
    const difference = (a[index] || 0) - (b[index] || 0);
    if (difference !== 0) return difference > 0 ? 1 : -1;
  }
  return 0;
}

// Choose the highest-version probe. Ties keep the earlier enumeration position,
// which favors PATH entries over well-known fallbacks.
export function pickBest(probes) {
  let best = null;
  for (const probe of probes) {
    if (!probe || !probe.version) continue;
    if (!best || compareVersions(probe.version, best.version) > 0) {
      best = probe;
    }
  }
  return best;
}

function versionLabel(version) {
  return version ? version.join('.') : null;
}

export class ClaudeBinaryResolver {
  constructor({
    exec = defaultExec,
    platform = process.platform,
    env = process.env,
    homedir = osHomedir(),
    diagnostic = () => {},
    probeTimeoutMs = DEFAULT_PROBE_TIMEOUT_MS,
    fileExists = existsSync,
  } = {}) {
    this.exec = exec;
    this.platform = platform;
    this.env = env;
    this.homedir = homedir;
    this.fileExists = fileExists;
    this.diagnostic = diagnostic;
    this.probeTimeoutMs = probeTimeoutMs;
    this.cached = null;
    this.pending = null;
  }

  // Returns the resolved absolute claude path (cached for the process lifetime).
  // Pass { refresh: true } to discard the cache and re-probe, which the session
  // registry uses when an invocation fails with an unknown-option error.
  async resolve({ refresh = false } = {}) {
    if (refresh) {
      this.cached = null;
    }
    if (this.cached) {
      return this.cached;
    }
    if (this.pending) {
      return this.pending;
    }
    this.pending = this.discover().finally(() => {
      this.pending = null;
    });
    return this.pending;
  }

  // The bare name is a working last resort on POSIX but not on Windows, where PATH search
  // never appends `.cmd`. A transient probe failure would otherwise cache a command that can
  // never be spawned, so the file itself is looked up before giving up on it.
  fallbackCommand() {
    return resolveExecutableOnPath(FALLBACK_COMMAND, {
      env: this.env,
      platform: this.platform,
      fileExists: this.fileExists,
    });
  }

  async probe(path) {
    try {
      // Probing has to use the same invocation shape execution uses. Probing `claude.cmd`
      // directly fails on Windows, which used to reject every shim install and fall back to
      // the bare `claude` name that cannot be spawned at all.
      const invocation = providerCommandInvocation(path, ['--version'], {
        platform: this.platform,
        env: this.env,
      });
      const stdout = await this.exec(invocation.command, invocation.args, {
        encoding: 'utf8',
        timeout: this.probeTimeoutMs,
        ...invocation.options,
      });
      const version = parseClaudeVersion(stdout);
      if (!version) {
        return { path, version: null, reason: 'unrecognized-version' };
      }
      return { path, version };
    } catch (error) {
      return { path, version: null, reason: error?.code || error?.message || 'probe-failed' };
    }
  }

  async discover() {
    try {
      const candidates = enumerateCandidates({
        env: this.env,
        platform: this.platform,
        homedir: this.homedir,
      });
      // Windows candidates are filtered to files that exist before anything is spawned. A
      // missing `.exe` costs nothing to probe because the spawn fails inside libuv, but a
      // missing `.cmd` now starts a real cmd.exe that then fails to find it, and a normal PATH
      // holds dozens of entries. POSIX keeps probing every candidate: there a probe is one
      // direct execFile, and deciding what is executable is the spawn's job, not a stat's.
      const probeable = this.platform === 'win32'
        ? candidates.filter((path) => {
          try {
            return this.fileExists(path);
          } catch {
            return false;
          }
        })
        : candidates;
      const probes = await Promise.all(probeable.map((path) => this.probe(path)));
      const best = pickBest(probes);
      if (!best) {
        this.cached = this.fallbackCommand();
        this.diagnostic('claude.binary.fallback', {
          command: this.cached,
          candidates: probes.map((probe) => ({ path: probe.path, reason: probe.reason })),
        });
        return this.cached;
      }
      this.cached = best.path;
      const rejected = probes
        .filter((probe) => probe.path !== best.path)
        .map((probe) => ({
          path: probe.path,
          version: versionLabel(probe.version),
          reason: probe.version ? 'lower-version' : (probe.reason || 'probe-failed'),
        }));
      this.diagnostic('claude.binary.resolved', {
        command: best.path,
        version: versionLabel(best.version),
        supportsAgentsJson: compareVersions(best.version, KNOWN_GOOD_VERSION) >= 0,
        rejected,
      });
      return this.cached;
    } catch (error) {
      this.cached = this.fallbackCommand();
      this.diagnostic('claude.binary.fallback', {
        command: this.cached,
        error: error?.message || 'resolution-failed',
      });
      return this.cached;
    }
  }
}

// Detects the exact failure the outdated 2.1.84 binary produces for
// `agents --json` so the registry can re-resolve to a newer binary and retry.
export function isUnknownOptionError(error) {
  const haystack = `${error?.stderr || ''}\n${error?.message || ''}`;
  return /unknown option/i.test(haystack);
}
